
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a python script
      run: python ./.github/workflows/build_file_list.py
    - name: set username
      run: git config --global user.name AUTOMATION
    - name: set email
      run: git config --global user.email "AUTOMATION@sudomagic.com"
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating TODO.txt"
    - name: fetch from master
      run: git fetch origin main
    - name: push code to master
      run: git push origin HEAD:main