
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os

            os.mkdir("manifest/")
            with open("manifest/test.txt", "w+") as file:
              file.write("Hello world")

            print("Directory contents:")
            for f in os.listdir():
                print(f)

